-- Copyright (C) 2018  Intel Corporation. All rights reserved.
-- Your use of Intel Corporation's design tools, logic functions 
-- and other software and tools, and its AMPP partner logic 
-- functions, and any output files from any of the foregoing 
-- (including device programming or simulation files), and any 
-- associated documentation or information are expressly subject 
-- to the terms and conditions of the Intel Program License 
-- Subscription Agreement, the Intel Quartus Prime License Agreement,
-- the Intel FPGA IP License Agreement, or other applicable license
-- agreement, including, without limitation, that your use is for
-- the sole purpose of programming logic devices manufactured by
-- Intel and sold by Intel or its authorized distributors.  Please
-- refer to the applicable agreement for further details.

-- Generated by Quartus Prime Version 18.1.0 Build 625 09/12/2018 SJ Lite Edition
-- Created on Mon Nov 10 16:31:34 2025

LIBRARY ieee;
USE ieee.std_logic_1164.all;

ENTITY JugacionMachine IS
    PORT (
        reset : IN STD_LOGIC := '0';
        clock : IN STD_LOGIC;
        Boton : IN STD_LOGIC := '0';
        Win : IN STD_LOGIC := '0';
        Habilitada : IN STD_LOGIC := '0';
        POSenable : IN STD_LOGIC := '0';
        win3 : IN STD_LOGIC := '0';
        final_win : OUT STD_LOGIC;
        Cambio : OUT STD_LOGIC;
        err : OUT STD_LOGIC;
        Verificacion : OUT STD_LOGIC
    );
END JugacionMachine;

ARCHITECTURE BEHAVIOR OF JugacionMachine IS
    TYPE type_fstate IS (Verificar,Error,Marcar,Punto,Ganar,Idle,CambioJ);
    SIGNAL fstate : type_fstate;
    SIGNAL reg_fstate : type_fstate;
BEGIN
    PROCESS (clock,reg_fstate)
    BEGIN
        IF (clock='1' AND clock'event) THEN
            fstate <= reg_fstate;
        END IF;
    END PROCESS;

    PROCESS (fstate,reset,Boton,Win,Habilitada,POSenable,win3)
    BEGIN
        IF (reset='1') THEN
            reg_fstate <= Idle;
            final_win <= '0';
            Cambio <= '0';
            err <= '0';
            Verificacion <= '0';
        ELSE
            final_win <= '0';
            Cambio <= '0';
            err <= '0';
            Verificacion <= '0';
            CASE fstate IS
                WHEN Verificar =>
                    IF (((Habilitada = '0') AND (POSenable = '1'))) THEN
                        reg_fstate <= Error;
                    ELSIF (((Habilitada = '1') AND (POSenable = '1'))) THEN
                        reg_fstate <= Marcar;
                    ELSIF ((POSenable = '0')) THEN
                        reg_fstate <= Verificar;
                    -- Inserting 'else' block to prevent latch inference
                    ELSE
                        reg_fstate <= Verificar;
                    END IF;

                    final_win <= '0';

                    Verificacion <= '1';

                    err <= '0';

                    Cambio <= '0';
                WHEN Error =>
                    reg_fstate <= Idle;

                    final_win <= '0';

                    Verificacion <= '0';

                    err <= '1';

                    Cambio <= '0';
                WHEN Marcar =>
                    IF ((Win = '1')) THEN
                        reg_fstate <= Punto;
                    ELSE
                        reg_fstate <= CambioJ;
                    END IF;

                    final_win <= '0';

                    Verificacion <= '0';

                    err <= '0';

                    Cambio <= '0';
                WHEN Punto =>
                    IF (((Win = '1') AND (win3 = '1'))) THEN
                        reg_fstate <= Ganar;
                    ELSE
                        reg_fstate <= CambioJ;
                    END IF;

                    final_win <= '0';

                    Verificacion <= '0';

                    err <= '0';

                    Cambio <= '0';
                WHEN Ganar =>
                    reg_fstate <= CambioJ;

                    final_win <= '1';

                    Verificacion <= '0';

                    err <= '0';

                    Cambio <= '0';
                WHEN Idle =>
                    IF ((Boton = '1')) THEN
                        reg_fstate <= Verificar;
                    ELSIF ((Boton = '0')) THEN
                        reg_fstate <= Idle;
                    -- Inserting 'else' block to prevent latch inference
                    ELSE
                        reg_fstate <= Idle;
                    END IF;

                    final_win <= '0';

                    Verificacion <= '0';

                    err <= '0';

                    Cambio <= '0';
                WHEN CambioJ =>
                    reg_fstate <= Idle;

                    final_win <= '0';

                    Verificacion <= '0';

                    err <= '0';

                    Cambio <= '1';
                WHEN OTHERS => 
                    final_win <= 'X';
                    Cambio <= 'X';
                    err <= 'X';
                    Verificacion <= 'X';
                    report "Reach undefined state";
            END CASE;
        END IF;
    END PROCESS;
END BEHAVIOR;
