// megafunction wizard: %LPM_DECODE%
// GENERATION: STANDARD
// VERSION: WM1.0
// MODULE: LPM_DECODE 

// ============================================================
// File Name: lpm_decode0.v
// Megafunction Name(s):
// 			LPM_DECODE
//
// Simulation Library Files(s):
// 			lpm
// ============================================================
// ************************************************************
// THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
//
// 13.0.1 Build 232 06/12/2013 SP 1 SJ Web Edition
// ************************************************************


//Copyright (C) 1991-2013 Altera Corporation
//Your use of Altera Corporation's design tools, logic functions 
//and other software and tools, and its AMPP partner logic 
//functions, and any output files from any of the foregoing 
//(including device programming or simulation files), and any 
//associated documentation or information are expressly subject 
//to the terms and conditions of the Altera Program License 
//Subscription Agreement, Altera MegaCore Function License 
//Agreement, or other applicable license agreement, including, 
//without limitation, that your use is for the sole purpose of 
//programming logic devices manufactured by Altera and sold by 
//Altera or its authorized distributors.  Please refer to the 
//applicable agreement for further details.


//lpm_decode DEVICE_FAMILY="Cyclone IV E" LPM_DECODES=16 LPM_WIDTH=4 data enable eq
//VERSION_BEGIN 13.0 cbx_cycloneii 2013:06:12:18:03:43:SJ cbx_lpm_add_sub 2013:06:12:18:03:43:SJ cbx_lpm_compare 2013:06:12:18:03:43:SJ cbx_lpm_decode 2013:06:12:18:03:43:SJ cbx_mgl 2013:06:12:18:05:10:SJ cbx_stratix 2013:06:12:18:03:43:SJ cbx_stratixii 2013:06:12:18:03:43:SJ  VERSION_END
// synthesis VERILOG_INPUT_VERSION VERILOG_2001
// altera message_off 10463


//synthesis_resources = lut 18 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
module  lpm_decode0_decode
	( 
	data,
	enable,
	eq) /* synthesis synthesis_clearbox=1 */;
	input   [3:0]  data;
	input   enable;
	output   [15:0]  eq;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri0   [3:0]  data;
	tri1   enable;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	wire  [3:0]  data_wire;
	wire  enable_wire;
	wire  [15:0]  eq_node;
	wire  [15:0]  eq_wire;
	wire  [1:0]  w_anode101w;
	wire  [3:0]  w_anode108w;
	wire  [3:0]  w_anode119w;
	wire  [3:0]  w_anode129w;
	wire  [3:0]  w_anode12w;
	wire  [3:0]  w_anode139w;
	wire  [3:0]  w_anode149w;
	wire  [3:0]  w_anode159w;
	wire  [3:0]  w_anode169w;
	wire  [3:0]  w_anode179w;
	wire  [3:0]  w_anode29w;
	wire  [3:0]  w_anode39w;
	wire  [1:0]  w_anode3w;
	wire  [3:0]  w_anode49w;
	wire  [3:0]  w_anode59w;
	wire  [3:0]  w_anode69w;
	wire  [3:0]  w_anode79w;
	wire  [3:0]  w_anode89w;
	wire  [2:0]  w_data1w;

	assign
		data_wire = data,
		enable_wire = enable,
		eq = eq_node,
		eq_node = eq_wire[15:0],
		eq_wire = {{w_anode179w[3], w_anode169w[3], w_anode159w[3], w_anode149w[3], w_anode139w[3], w_anode129w[3], w_anode119w[3], w_anode108w[3]}, {w_anode89w[3], w_anode79w[3], w_anode69w[3], w_anode59w[3], w_anode49w[3], w_anode39w[3], w_anode29w[3], w_anode12w[3]}},
		w_anode101w = {(w_anode101w[0] & data_wire[3]), enable_wire},
		w_anode108w = {(w_anode108w[2] & (~ w_data1w[2])), (w_anode108w[1] & (~ w_data1w[1])), (w_anode108w[0] & (~ w_data1w[0])), w_anode101w[1]},
		w_anode119w = {(w_anode119w[2] & (~ w_data1w[2])), (w_anode119w[1] & (~ w_data1w[1])), (w_anode119w[0] & w_data1w[0]), w_anode101w[1]},
		w_anode129w = {(w_anode129w[2] & (~ w_data1w[2])), (w_anode129w[1] & w_data1w[1]), (w_anode129w[0] & (~ w_data1w[0])), w_anode101w[1]},
		w_anode12w = {(w_anode12w[2] & (~ w_data1w[2])), (w_anode12w[1] & (~ w_data1w[1])), (w_anode12w[0] & (~ w_data1w[0])), w_anode3w[1]},
		w_anode139w = {(w_anode139w[2] & (~ w_data1w[2])), (w_anode139w[1] & w_data1w[1]), (w_anode139w[0] & w_data1w[0]), w_anode101w[1]},
		w_anode149w = {(w_anode149w[2] & w_data1w[2]), (w_anode149w[1] & (~ w_data1w[1])), (w_anode149w[0] & (~ w_data1w[0])), w_anode101w[1]},
		w_anode159w = {(w_anode159w[2] & w_data1w[2]), (w_anode159w[1] & (~ w_data1w[1])), (w_anode159w[0] & w_data1w[0]), w_anode101w[1]},
		w_anode169w = {(w_anode169w[2] & w_data1w[2]), (w_anode169w[1] & w_data1w[1]), (w_anode169w[0] & (~ w_data1w[0])), w_anode101w[1]},
		w_anode179w = {(w_anode179w[2] & w_data1w[2]), (w_anode179w[1] & w_data1w[1]), (w_anode179w[0] & w_data1w[0]), w_anode101w[1]},
		w_anode29w = {(w_anode29w[2] & (~ w_data1w[2])), (w_anode29w[1] & (~ w_data1w[1])), (w_anode29w[0] & w_data1w[0]), w_anode3w[1]},
		w_anode39w = {(w_anode39w[2] & (~ w_data1w[2])), (w_anode39w[1] & w_data1w[1]), (w_anode39w[0] & (~ w_data1w[0])), w_anode3w[1]},
		w_anode3w = {(w_anode3w[0] & (~ data_wire[3])), enable_wire},
		w_anode49w = {(w_anode49w[2] & (~ w_data1w[2])), (w_anode49w[1] & w_data1w[1]), (w_anode49w[0] & w_data1w[0]), w_anode3w[1]},
		w_anode59w = {(w_anode59w[2] & w_data1w[2]), (w_anode59w[1] & (~ w_data1w[1])), (w_anode59w[0] & (~ w_data1w[0])), w_anode3w[1]},
		w_anode69w = {(w_anode69w[2] & w_data1w[2]), (w_anode69w[1] & (~ w_data1w[1])), (w_anode69w[0] & w_data1w[0]), w_anode3w[1]},
		w_anode79w = {(w_anode79w[2] & w_data1w[2]), (w_anode79w[1] & w_data1w[1]), (w_anode79w[0] & (~ w_data1w[0])), w_anode3w[1]},
		w_anode89w = {(w_anode89w[2] & w_data1w[2]), (w_anode89w[1] & w_data1w[1]), (w_anode89w[0] & w_data1w[0]), w_anode3w[1]},
		w_data1w = data_wire[2:0];
endmodule //lpm_decode0_decode
//VALID FILE


// synopsys translate_off
`timescale 1 ps / 1 ps
// synopsys translate_on
module lpm_decode0 (
	data,
	enable,
	eq1,
	eq2,
	eq3,
	eq4,
	eq5,
	eq6,
	eq7,
	eq8,
	eq9)/* synthesis synthesis_clearbox = 1 */;

	input	[3:0]  data;
	input	  enable;
	output	  eq1;
	output	  eq2;
	output	  eq3;
	output	  eq4;
	output	  eq5;
	output	  eq6;
	output	  eq7;
	output	  eq8;
	output	  eq9;

	wire [15:0] sub_wire0;
	wire [8:8] sub_wire9 = sub_wire0[8:8];
	wire [4:4] sub_wire8 = sub_wire0[4:4];
	wire [9:9] sub_wire7 = sub_wire0[9:9];
	wire [7:7] sub_wire6 = sub_wire0[7:7];
	wire [5:5] sub_wire5 = sub_wire0[5:5];
	wire [3:3] sub_wire4 = sub_wire0[3:3];
	wire [1:1] sub_wire3 = sub_wire0[1:1];
	wire [6:6] sub_wire2 = sub_wire0[6:6];
	wire [2:2] sub_wire1 = sub_wire0[2:2];
	wire  eq2 = sub_wire1;
	wire  eq6 = sub_wire2;
	wire  eq1 = sub_wire3;
	wire  eq3 = sub_wire4;
	wire  eq5 = sub_wire5;
	wire  eq7 = sub_wire6;
	wire  eq9 = sub_wire7;
	wire  eq4 = sub_wire8;
	wire  eq8 = sub_wire9;

	lpm_decode0_decode	lpm_decode0_decode_component (
				.data (data),
				.enable (enable),
				.eq (sub_wire0));

endmodule

// ============================================================
// CNX file retrieval info
// ============================================================
// Retrieval info: PRIVATE: BaseDec NUMERIC "1"
// Retrieval info: PRIVATE: EnableInput NUMERIC "1"
// Retrieval info: PRIVATE: INTENDED_DEVICE_FAMILY STRING "Cyclone IV E"
// Retrieval info: PRIVATE: LPM_PIPELINE NUMERIC "0"
// Retrieval info: PRIVATE: Latency NUMERIC "0"
// Retrieval info: PRIVATE: SYNTH_WRAPPER_GEN_POSTFIX STRING "1"
// Retrieval info: PRIVATE: aclr NUMERIC "0"
// Retrieval info: PRIVATE: clken NUMERIC "0"
// Retrieval info: PRIVATE: eq0 NUMERIC "0"
// Retrieval info: PRIVATE: eq1 NUMERIC "1"
// Retrieval info: PRIVATE: eq10 NUMERIC "0"
// Retrieval info: PRIVATE: eq11 NUMERIC "0"
// Retrieval info: PRIVATE: eq12 NUMERIC "0"
// Retrieval info: PRIVATE: eq13 NUMERIC "0"
// Retrieval info: PRIVATE: eq14 NUMERIC "0"
// Retrieval info: PRIVATE: eq15 NUMERIC "0"
// Retrieval info: PRIVATE: eq2 NUMERIC "1"
// Retrieval info: PRIVATE: eq3 NUMERIC "1"
// Retrieval info: PRIVATE: eq4 NUMERIC "1"
// Retrieval info: PRIVATE: eq5 NUMERIC "1"
// Retrieval info: PRIVATE: eq6 NUMERIC "1"
// Retrieval info: PRIVATE: eq7 NUMERIC "1"
// Retrieval info: PRIVATE: eq8 NUMERIC "1"
// Retrieval info: PRIVATE: eq9 NUMERIC "1"
// Retrieval info: PRIVATE: nBit NUMERIC "4"
// Retrieval info: PRIVATE: new_diagram STRING "1"
// Retrieval info: LIBRARY: lpm lpm.lpm_components.all
// Retrieval info: CONSTANT: LPM_DECODES NUMERIC "16"
// Retrieval info: CONSTANT: LPM_TYPE STRING "LPM_DECODE"
// Retrieval info: CONSTANT: LPM_WIDTH NUMERIC "4"
// Retrieval info: USED_PORT: @eq 0 0 16 0 OUTPUT NODEFVAL "@eq[15..0]"
// Retrieval info: USED_PORT: data 0 0 4 0 INPUT NODEFVAL "data[3..0]"
// Retrieval info: USED_PORT: enable 0 0 0 0 INPUT NODEFVAL "enable"
// Retrieval info: USED_PORT: eq1 0 0 0 0 OUTPUT NODEFVAL "eq1"
// Retrieval info: USED_PORT: eq2 0 0 0 0 OUTPUT NODEFVAL "eq2"
// Retrieval info: USED_PORT: eq3 0 0 0 0 OUTPUT NODEFVAL "eq3"
// Retrieval info: USED_PORT: eq4 0 0 0 0 OUTPUT NODEFVAL "eq4"
// Retrieval info: USED_PORT: eq5 0 0 0 0 OUTPUT NODEFVAL "eq5"
// Retrieval info: USED_PORT: eq6 0 0 0 0 OUTPUT NODEFVAL "eq6"
// Retrieval info: USED_PORT: eq7 0 0 0 0 OUTPUT NODEFVAL "eq7"
// Retrieval info: USED_PORT: eq8 0 0 0 0 OUTPUT NODEFVAL "eq8"
// Retrieval info: USED_PORT: eq9 0 0 0 0 OUTPUT NODEFVAL "eq9"
// Retrieval info: CONNECT: @data 0 0 4 0 data 0 0 4 0
// Retrieval info: CONNECT: @enable 0 0 0 0 enable 0 0 0 0
// Retrieval info: CONNECT: eq1 0 0 0 0 @eq 0 0 1 1
// Retrieval info: CONNECT: eq2 0 0 0 0 @eq 0 0 1 2
// Retrieval info: CONNECT: eq3 0 0 0 0 @eq 0 0 1 3
// Retrieval info: CONNECT: eq4 0 0 0 0 @eq 0 0 1 4
// Retrieval info: CONNECT: eq5 0 0 0 0 @eq 0 0 1 5
// Retrieval info: CONNECT: eq6 0 0 0 0 @eq 0 0 1 6
// Retrieval info: CONNECT: eq7 0 0 0 0 @eq 0 0 1 7
// Retrieval info: CONNECT: eq8 0 0 0 0 @eq 0 0 1 8
// Retrieval info: CONNECT: eq9 0 0 0 0 @eq 0 0 1 9
// Retrieval info: GEN_FILE: TYPE_NORMAL lpm_decode0.vhd TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL lpm_decode0.inc TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL lpm_decode0.cmp TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL lpm_decode0.bsf TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL lpm_decode0_inst.vhd TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL lpm_decode0_syn.v TRUE
// Retrieval info: LIB_FILE: lpm
