-- Copyright (C) 1991-2013 Altera Corporation
-- Your use of Altera Corporation's design tools, logic functions 
-- and other software and tools, and its AMPP partner logic 
-- functions, and any output files from any of the foregoing 
-- (including device programming or simulation files), and any 
-- associated documentation or information are expressly subject 
-- to the terms and conditions of the Altera Program License 
-- Subscription Agreement, Altera MegaCore Function License 
-- Agreement, or other applicable license agreement, including, 
-- without limitation, that your use is for the sole purpose of 
-- programming logic devices manufactured by Altera and sold by 
-- Altera or its authorized distributors.  Please refer to the 
-- applicable agreement for further details.

-- Generated by Quartus II Version 13.0.1 Build 232 06/12/2013 Service Pack 1 SJ Web Edition
-- Created on Thu Nov 13 14:09:29 2025

LIBRARY ieee;
USE ieee.std_logic_1164.all;

ENTITY SeleccionJugador IS
    PORT (
        reset : IN STD_LOGIC := '0';
        clock : IN STD_LOGIC;
        Enable : IN STD_LOGIC := '0';
        Jugada : IN STD_LOGIC := '0';
        Jugador : OUT STD_LOGIC;
        Hab : OUT STD_LOGIC
    );
END SeleccionJugador;

ARCHITECTURE BEHAVIOR OF SeleccionJugador IS
    TYPE type_fstate IS (JuegaP1,JuegaP2,Oscioso2,Oscioso1);
    SIGNAL fstate : type_fstate;
    SIGNAL reg_fstate : type_fstate;
BEGIN
    PROCESS (clock,reg_fstate)
    BEGIN
        IF (clock='1' AND clock'event) THEN
            fstate <= reg_fstate;
        END IF;
    END PROCESS;

    PROCESS (fstate,reset,Enable,Jugada)
    BEGIN
        IF (reset='1') THEN
            reg_fstate <= JuegaP1;
            Jugador <= '0';
            Hab <= '0';
        ELSE
            Jugador <= '0';
            Hab <= '0';
            CASE fstate IS
                WHEN JuegaP1 =>
                    IF (((Enable = '1') AND (Jugada = '1'))) THEN
                        reg_fstate <= Oscioso1;
                    ELSIF ((Enable = '0')) THEN
                        reg_fstate <= JuegaP1;
                    -- Inserting 'else' block to prevent latch inference
                    ELSE
                        reg_fstate <= JuegaP1;
                    END IF;

                    Hab <= '0';

                    Jugador <= '0';
                WHEN JuegaP2 =>
                    IF ((Enable = '0')) THEN
                        reg_fstate <= JuegaP2;
                    ELSIF (((Enable = '1') AND (Jugada = '1'))) THEN
                        reg_fstate <= Oscioso2;
                    -- Inserting 'else' block to prevent latch inference
                    ELSE
                        reg_fstate <= JuegaP2;
                    END IF;

                    Hab <= '0';

                    Jugador <= '1';
                WHEN Oscioso2 =>
                    reg_fstate <= JuegaP1;

                    Hab <= '1';

                    Jugador <= '1';
                WHEN Oscioso1 =>
                    reg_fstate <= JuegaP2;

                    Hab <= '1';

                    Jugador <= '0';
                WHEN OTHERS => 
                    Jugador <= 'X';
                    Hab <= 'X';
                    report "Reach undefined state";
            END CASE;
        END IF;
    END PROCESS;
END BEHAVIOR;
